### ISSUE TITLE
Sass Architecture

### ISSUE THREAD

**Issue by andyhqtran** [elegantthemes/Divi-Beta#318]
### Problem:

This ticket will document the issues we're facing with our sass files, and the steps we need to take to clean it up for the developer update. Ideally, we should get as much tackled out before the release, but it's low priority.
## 
### Todos:
- [ ] 1. Create our own "Standard" for CSS.
- [ ] 2. Set-up a global `variables.js` that we can pass via the `style-loader` for webpack.
- [ ] 3. Move all the styles in `style.scss` to it's proper component folder
- [ ] 4. Create a `mixin` that will include all the base fonts for our application to prevent other themes from overwriting it. Note: This should be the only global mixin we use for the time being.
- [ ] 5. Remove any `@keyframes` that we're using in our project.
- [ ] 6. Create a body class the allow use to specify our styles.
- [ ] 7. Get rid of `!important` in our code.
- [ ] 8. Properly document our scss files.
## 
### Examples:

``` scss
// Global Imports
@import '../modules/base';
@import '../modules/mixins';

// Button.scss

// Button
.button {
  @include base-font();

  &__element-1 {}

  &__element-2 {}

  // Icon
  .icon { ... }
}

// Button (Color)
.button {
  &--color-1 {}

  &--color-2 {}
}

// Button (Type)
.button {
  &--type-1 {}

  &--type-2 {}
}
```
