### ISSUE TITLE
Builder Sync, Auto-Save, Browser Backups & Shortcode Object Bloat Reduction

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#912]
I am creating a new issue for PR 575, which now includes both the shortcode object optimization branch and the builder sync / auto-save branch. We can use this to track issues with the combined branches.

The attached branches contain the following features and improvements:

## Divi Builder Sync

When a user has two tabs open, with both the Backend Builder and the Visual Builder open for the same page, changes made in either tab should be synced with the other tab once the user returns to it. For example, if someone makes a change to the page in the Visual Builder in one tab, and then switches over the Backend Builder in their second tab where the Backend Builder is active for the same page, the changes are loaded in via Ajax. This prevents people from accidentally overwriting their changes. We need to make sure that know quirkiness exists with this syncing activity. 

#### Known Issues
- [x] The sync has significant delay from being activated / focused, AJAX call being triggered, and the result being  returned. It takes about 10 seconds when refreshing the page and reloading the builder would take 1 second. It's quite frustrating for that reason.
- [x] The sync doesn't always happen. For example, it doesn't work in the following scenario: 1) Add new page, load `homepage basic` pre-defined layout, 2) Publish page, open VB on different tab, 3) On VB, removed all section except for one, 4) switch to BB; the BB page doesn't sync to its VB counterpart
- [x] broken section with no row on BB. VB supports no-row situation while BB requires a section to always have a row. When all row is removed on VB then it get synced to BB, it doesn't look good (Note: I feel like we've fixed this before but somehow it happens again):

![no-row support on bb](https://cloud.githubusercontent.com/assets/916442/22395895/ef430072-e57d-11e6-99ea-7ac36c963551.jpg)
- [x] BB layout doesn't get locked when BB is syncing with changes happen on VB. On VB, when it fetches for sync data,  the layout is locked until the ajax call returns. This avoid the layout being changed when the auto save data arrive. On BB, there is no such lock, causing the layout can be different with auto save data is arrived.
- [x] After bouncing back between different tabs and saving in each, the following error eventually occurs. It has happened to me multiple times in this branch:

<img width="1237" alt="screen shot 2017-01-28 at 9 49 00 am" src="https://cloud.githubusercontent.com/assets/3333028/22398524/1d3603d8-e53f-11e6-8bb6-0e6f6fa1acb7.png">

## Auto-Saves

Auto-saves are now saved in the backgrounds to the database when someone is making changes to their page in the Visual Builder. If something happens, such as their computer crashing, the next time they open up the Visual Builder it will detect that the auto-save is newer than the current version of the page, and it will give them the option to restore it. Auto-Saves should be discarded when someone purposefully leaves the builder and choses not to save. If they leave the page and are greeted with the "You Have Unsaved Changes" modal and they choose to "Discard & Exit," it should also discard the auto-save. We don't want to annoy people with auto-save modals every time they load the page when they obviously didn't want to save those changes. We only want to provide the option to restore when we think they might have mistakenly lost their changes. 

## Browser Backups

In additional auto-saves, backups of the post are stored in the browser. Much like auto-saves, these session-based backups stored in localstorage can be used to retrieve lost data when something goes wrong. 

#### Known Issues
- [x] When restoring a browser backup that contain a portfolio module, filterable portfolio module or fullwidth portfolio module, the following error occurs:
![screen shot 2017-01-30 at 7 26 43 pm](https://cloud.githubusercontent.com/assets/3333028/22451295/37d6e7b8-e722-11e6-945b-02a444a5478b.png)

- [x] When restoring a layout that contains a post navigation module, the following error occurs:

![screen shot 2017-01-31 at 4 52 48 pm](https://cloud.githubusercontent.com/assets/3333028/22491082/e07f5414-e7d5-11e6-91cb-dec9b1cfa831.png)

- [x] When restoring a layout that contains a post slider module, the following error occurs:

![screen shot 2017-01-31 at 4 54 32 pm](https://cloud.githubusercontent.com/assets/3333028/22491107/fdce47b4-e7d5-11e6-8415-f9beeb4db577.png)

- [x] When restoring a layout that contains a gallery module, the following error occurs: 

![screen shot 2017-01-31 at 4 55 42 pm](https://cloud.githubusercontent.com/assets/3333028/22491136/2a31c15a-e7d6-11e6-8802-33266f8d026c.png)

- [x] When restoring a layout that contains a map module, the following error occurs:

![screen shot 2017-01-31 at 4 57 35 pm](https://cloud.githubusercontent.com/assets/3333028/22491166/70847ab2-e7d6-11e6-90aa-5957dae9a30c.png)

## Shortcode Bloat Reduction

This PR changes the way that the VB receives shortcode content. It no longer fills in all shortcode attributes with default values. Instead, we want it to work like the Backend Builder where empty or default values are interpreted correctly. This allows us to greatly reduce the size of the shortcode object being saves, which will help reduce the frequency of failed saves on certain hosts that limit post sizes or have insufficient resources to send large posts. This introduces a significant problems for the Visual Builder, however, since the Visual Builder has been relying on all of these explicit default values to function. We need to make sure that all options are rendering correct in the Visual Builder. 

#### Known Issue
- [x] Broken layout, caused by attribute with default value being trimmed during page load. Proposed fix: https://github.com/elegantthemes/submodule-builder/pull/1641
- [x] Adding the Contact Form module to the page returns an error. Fixed at https://github.com/elegantthemes/submodule-builder/pull/1641
- [x]  The History modal is broken. Fixed at https://github.com/elegantthemes/submodule-builder/pull/1641
- [x] Hovering over Fullwidth Header modules returns an error. Also, their settings modals cannot be opened. (try the Homepage Basic layout). Fixed at https://github.com/elegantthemes/submodule-builder/pull/1641

## Attached PRs
- https://github.com/elegantthemes/submodule-builder/pull/1267
- https://github.com/elegantthemes/submodule-core/pull/43

**Comment by fikrirasyid** [comment]
@timayhelen there are four issues that I've fixed on https://github.com/elegantthemes/submodule-builder/pull/1641:

- Broken layout, caused by attribute with default value being trimmed during page load. 
- Adding the Contact Form module to the page returns an error. 

These two issues are original issues that appear on `575-fix-heartbeat-content-smashing` branch. On the other hand, the other two issues actually have been fixed at `master` so I cherry-picked the fix on master to https://github.com/elegantthemes/submodule-builder/issues/1641

**Comment by fikrirasyid** [comment]
@Jronk @timayhelen 

I've submitted https://github.com/elegantthemes/submodule-builder/pull/1659 which fixes two Builder Sync related issues mentioned above.

I'm still working on the first two Builder sync issue.

Related to the last builder sync issue, I'm unable to replicate it. It seems to be lack of table-existence issue but we already have table checking there. I think it has something to do with the installation. What is weird from your screenshot is:

![table-issues](https://cloud.githubusercontent.com/assets/916442/22465007/322dd8f6-e7ec-11e6-94f7-52f15256456c.jpg)

To check this, can you do the following?

1. Paste this on your functions.php

```
function et_dev_show_db_name( $row ) {
	return reset($row);
}

function et_dev_show_db_names() {
	global $wpdb;

	$sql = "SHOW TABLES LIKE '%'";
	$results = $wpdb->get_results($sql);

	echo '<pre>';
	print_r( array_map( 'et_dev_show_db_name', $results ) );
	echo '</pre>';

	die();
}
add_action( 'wp_ajax_show_database_tables', 'et_dev_show_db_names' );
```

2. Open `http://your_local_site_dir/wp-admin/admin-ajax.php?action=show_database_tables`
3. Copy the table list and paste them here.

**Comment by fikrirasyid** [comment]
@Jronk @timayhelen I've submitted a PR for fixing the browser backup issues: https://github.com/elegantthemes/submodule-builder/pull/1662

Note: I merged `master` to the PR because colorpicker issue that appear on the PR (which also exists on  `575-fix-heartbeat-content-smashing`) has been fixed on `master`

**Comment by fikrirasyid** [comment]
It appears that recent changes added by @Jronk on `575-fix-hearbeat-content-smashing` has fixed the following issue:

> The sync has significant delay from being activated / focused, AJAX call being triggered, and the result being returned. It takes about 10 seconds when refreshing the page and reloading the builder would take 1 second. It's quite frustrating for that reason.

The builder sync works more responsive now

**Comment by fikrirasyid** [comment]
It appears that recent changes added by @Jronk on `575-fix-heartbeat-content-smashing` has fixed this following issue as well:

> The sync doesn't always happen. For example, it doesn't work in the following scenario: 1) Add new page, load homepage basic pre-defined layout, 2) Publish page, open VB on different tab, 3) On VB, removed all section except for one, 4) switch to BB; the BB page doesn't sync to its VB counterpart

The only issue occurs regarding this, is that if I switch the tab before the heartbeat kicks in. However, I think it is inevitable tho.
